configuration: 
  name: dsoqa
  author: oaqa
  
persistence-provider:
  inherit: dsoqa.db.local-persistence-provider

collection-reader:
  inherit: helloqa.collection.decorated-collection-reader
  dataset: GUTENBERG
  file: /input/small.txt
#  inherit: fs.dir-collection-reader
#  dataset: GUTENBERG
#  suffix: txt
#  dir: /input

pipeline:
  - inherit: jdbc.sqlite.cse.phase  
    name: keyterm-extractor
    options: |
      - inherit: dsoqa.keyterm.simple

  - inherit: jdbc.sqlite.cse.phase 
    name: retrieval-strategist
    options: |
      - inherit: dsoqa.retrieval.simple-solr-strategist
          
  - inherit: jdbc.sqlite.cse.phase  
    name: passage-extractor
    options: |
      - inherit: dsoqa.passage.simple
      
  - inherit: dsoqa.eval.keyterm-aggregator-consumer

  - inherit: jdbc.eval.retrieval-aggregator-consumer
      
  - inherit: dsoqa.eval.passage-map-aggregator-consumer      
    
post-process: 
  - inherit: dsoqa.eval.keyterm-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: dsoqa.report.keyterm-report-component

  - inherit: jdbc.eval.retrieval-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: jdbc.report.f-measure-report-component
          
  - inherit: dsoqa.eval.passage-map-evaluator-consumer
  - inherit: report.csv-report-generator
    builders: |
      - inherit: dsoqa.report.map-report-component
  